name: Supabase Migrations

on:
  # Run actual migrations on push to main (including PR merges)
  push:
    branches: [ main ]
  # Run dry-run validation on PRs
  pull_request:

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Link to Supabase project
      run: npx supabase link --project-ref $SUPABASE_PROJECT_ID

    - name: Run database migrations
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npx supabase db push

    - name: Verify migrations (dry run) for PRs
      if: github.event_name == 'pull_request'
      run: npx supabase db push --dry-run
